# Example Site settings
url: "https://hjyoon.github.io"

#google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - peter.md
  - about.md
  - contact.md

footer: '<a href="https://github.com/hjyoon">github</a>'

#style: light # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
